function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function session(){const {data}=await supabaseClient.auth.getSession();if(data.session){login.classList.add("hidden");dashboard.classList.remove("hidden");await render()}else{login.classList.remove("hidden");dashboard.classList.add("hidden")}}
async function login(){const emailV=document.getElementById("email").value.trim(),pass=document.getElementById("password").value;const {error}=await supabaseClient.auth.signInWithPassword({email:emailV,password:pass});document.getElementById("loginStatus").textContent=error?error.message:"";if(!error)await session()}
async function logout(){await supabaseClient.auth.signOut();await session()}
async function resetPassword(){const emailV=document.getElementById("email").value.trim();if(!emailV)return alert("Введите email.");const {error}=await supabaseClient.auth.resetPasswordForEmail(emailV,{redirectTo:location.href});alert(error?error.message:"Письмо отправлено.")}
async function getProducts(){const {data,error}=await supabaseClient.from("products").select("*").order("created_at");if(error){document.getElementById("status").textContent=error.message;return[]}return data||[]}
async function render(){const a=await getProducts();document.getElementById("status").textContent="Онлайн-база • "+a.length+" товаров";document.getElementById("list").innerHTML=a.map(p=>`<div class="item"><div class="thumb">${p.image_url?`<img src="${p.image_url}">`:"amiii"}</div><div><div class="formgrid"><input id="n-${p.id}" class="field" value="${esc(p.name)}"><input id="p-${p.id}" class="field" type="number" value="${p.price}"></div><input id="d-${p.id}" class="field" value="${esc(p.description||"")}"><div class="actions"><button class="primary" onclick="saveProduct('${p.id}')">Сохранить</button><label class="secondary">Заменить фото<input type="file" accept="image/*" style="display:none" onchange="replacePhoto('${p.id}',this)"></label><button class="danger" onclick="deleteProduct('${p.id}')">Удалить</button></div></div></div>`).join("")}
async function uploadImage(file){const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=crypto.randomUUID()+"."+ext;const {error}=await supabaseClient.storage.from("product-images").upload(path,file,{upsert:false});if(error)throw error;return supabaseClient.storage.from("product-images").getPublicUrl(path).data.publicUrl}
async function addProduct(){try{const nameV=document.getElementById("name").value.trim(),priceV=Number(document.getElementById("price").value)||0,descV=document.getElementById("desc").value.trim(),file=document.getElementById("image").files[0];if(!nameV)return alert("Введите название.");const image_url=file?await uploadImage(file):"";const {error}=await supabaseClient.from("products").insert({name:nameV,price:priceV,description:descV,image_url});if(error)throw error;name.value="";price.value="";desc.value="";image.value="";await render()}catch(e){alert(e.message)}}
async function saveProduct(id){const {error}=await supabaseClient.from("products").update({name:document.getElementById("n-"+id).value.trim(),price:Number(document.getElementById("p-"+id).value)||0,description:document.getElementById("d-"+id).value.trim()}).eq("id",id);if(error)alert(error.message);else await render()}
async function replacePhoto(id,input){try{if(!input.files[0])return;const url=await uploadImage(input.files[0]);const {error}=await supabaseClient.from("products").update({image_url:url}).eq("id",id);if(error)throw error;await render()}catch(e){alert(e.message)}}
async function deleteProduct(id){if(!confirm("Удалить товар?"))return;const {error}=await supabaseClient.from("products").delete().eq("id",id);if(error)alert(error.message);else await render()}
supabaseClient.auth.onAuthStateChange(()=>session());session();