const PHONE="79810002221",CART="amiii_glow_cart";
function money(n){return new Intl.NumberFormat("ru-RU").format(n)+" ₽"}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function cart(){try{return JSON.parse(localStorage.getItem(CART))||[]}catch{return[]}}function saveCart(c){localStorage.setItem(CART,JSON.stringify(c))}
async function products(){const {data,error}=await supabaseClient.from("products").select("*").order("created_at");if(error){console.error(error);return[]}return data||[]}
async function render(){const p=await products();document.getElementById("productCount").textContent=p.length+" товаров";document.getElementById("products").innerHTML=p.map(x=>`<article class="product"><div class="photo">${x.image_url?`<img src="${x.image_url}" alt="${esc(x.name)}">`:`<div class="placeholder">amiii_glow</div>`}</div><div class="info"><h3>${esc(x.name)}</h3><div class="desc">${esc(x.description)}</div><div class="row"><span class="price">${money(x.price)}</span><button class="add" onclick='add(${JSON.stringify(x)})'>+</button></div></div></article>`).join("");renderCart()}
function add(p){let c=cart(),q=c.find(x=>x.id===p.id);q?q.qty++:c.push({...p,qty:1});saveCart(c);renderCart();toggleCart(true)}
function change(id,d){let c=cart(),q=c.find(x=>x.id===id);if(q){q.qty+=d;if(q.qty<=0)c=c.filter(x=>x.id!==id)}saveCart(c);renderCart()}function removeItem(id){saveCart(cart().filter(x=>x.id!==id));renderCart()}
function renderCart(){let c=cart();document.getElementById("cartCount").textContent=c.reduce((s,x)=>s+x.qty,0);document.getElementById("cartItems").innerHTML=c.length?c.map(x=>`<div class="cart-item"><div>${x.image_url?`<img class="thumb" src="${x.image_url}">`:"<div class='thumb'></div>"}</div><div><b>${esc(x.name)}</b><small>${money(x.price)}</small><div class="qty"><button onclick="change('${x.id}',-1)">−</button>${x.qty}<button onclick="change('${x.id}',1)">+</button></div></div><button class="remove" onclick="removeItem('${x.id}')">Удалить</button></div>`).join(""):"<p style='color:#8c747b'>Корзина пока пуста.</p>";document.getElementById("cartTotal").textContent=money(c.reduce((s,x)=>s+x.price*x.qty,0))}
function toggleCart(force){const o=document.getElementById("cartOverlay");o.classList.toggle("open",force===true?true:!o.classList.contains("open"))}
function checkout(){const c=cart();if(!c.length)return alert("Добавьте товар в корзину.");const total=c.reduce((s,x)=>s+x.price*x.qty,0),lines=c.map(x=>`${x.name} × ${x.qty} — ${money(x.price*x.qty)}`).join("\n"),msg=`Здравствуйте! Хочу оформить заказ в amiii_glow:\n\n${lines}\n\nИтого: ${money(total)}`;window.open("https://wa.me/"+PHONE+"?text="+encodeURIComponent(msg),"_blank")}
render();